# Generated by Django 3.1.14 on 2023-07-14 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('city', 'state')},
                'index_together': {('city', 'state')},
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('org_name', models.CharField(max_length=255)),
                ('posted_date', models.DateTimeField()),
                ('close_date', models.DateTimeField(null=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usa_jobs.location')),
            ],
            options={
                'unique_together': {('location', 'title', 'org_name', 'posted_date', 'date_updated')},
                'index_together': {('location', 'title', 'org_name', 'posted_date', 'date_updated')},
            },
        ),
    ]
