# Generated by Django 3.1.14 on 2023-07-15 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usa_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='job',
            unique_together={('location', 'title', 'org_name', 'posted_date', 'close_date')},
        ),
        migrations.AlterIndexTogether(
            name='job',
            index_together={('posted_date',), ('location', 'title')},
        ),
        migrations.CreateModel(
            name='RelatedOrgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=255)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usa_jobs.job')),
            ],
        ),
    ]
