# Generated by Django 3.1.14 on 2023-07-15 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usa_jobs', '0002_auto_20230715_0530'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='job',
            index_together={('posted_date', 'title'), ('location', 'title')},
        ),
    ]
